development:
  adapter: postgresql
  encoding: unicode
  database: some_dev
  pool: 5
  username: diethart
  password: Gfifhiuh4334

test:
  adapter: postgresql
  encoding: unicode
  database: some_test
  pool: 5
  username: diethart
  password: Gfifhiuh4334
