development:
  adapter: postgresql
  encoding: unicode
  database: some_dev
  pool: 5
  username: diethart
  password: Gfifhiuh4334

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TRAVIS'] ? 'travis_ci_test' : 'some_test' %>
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'diethart' %>
  password: <%= ENV['TRAVIS'] ? '' : 'Gfifhiuh4334' %>
